### ISSUE TITLE
$releasever RHEL 7

### ISSUE THREAD

**Issue by Carus11** [NeCTAR-RC/puppet-mariadb#14]
On rhel 7 I find that $releasever in manifests/repo/redhat.pp is evaluating as '7Server' instead of '7' as is required by mariadb repo http://yum.mariadb.org/10.0/rhel7-amd64/

it could be replaced with ${operatingsystemmajrelease}

**Comment by sorrison** [comment]
This look good https://review.rc.nectar.org.au/#/c/2224/1/manifests/repo/redhat.pp

**Comment by andrewspiers** [comment]
I think we should be able to use the yum variable $releasever here, ie

[root@andrewcen5 ~]# python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: fastestmirror
{'arch': 'ia32e',
 'basearch': 'x86_64',
 'releasever': '5'}


[root@hereford ~]# python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: fastestmirror
{'arch': 'amd64',
 'basearch': 'x86_64',
 'infra': 'stock',
 'releasever': '7',
 'uuid': '177f1415-27d2-4483-8aa1-78cd0b4ece75'}

**Comment by Carus11** [comment]
Running the same line on my RHEL 7 vm:

```
[root@SMGMT02 ~]# python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: product-id
{'arch': 'ia32e',
 'basearch': 'x86_64',
 'releasever': '7Server',
 'uuid': '38c5cebb-94a1-418d-8eef-4832c86253aa'}
```

related issue with the puppet repo? https://groups.google.com/forum/#!msg/puppet-users/-O-41ztdbAk/cPhlnqcnqrsJ


It may be better if I brought this up with MariaDB, to create the links in their yum repository

**Comment by sorrison** [comment]
Yeah not sure how to deal with this. Happy to take a pull request though if you do.

**Comment by sorrison** [comment]
expired
