### ISSUE TITLE
Could not find stage setup

### ISSUE THREAD

**Issue by mortzel** [NeCTAR-RC/puppet-mariadb#17]
Getting following error when trieing to install a galera cluster
`Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find stage setup specified by Class[Mariadb::Repo::Debian] at /etc/puppet/modules/mariadb/manifests/init.pp:38`

Puppet Version: 3.4.3-1
Distro: Ubuntu 14.04/12.04

**Comment by sorrison** [comment]
Hi mortzel,

We use puppetlabs/stdlib class stdlib::stages maybe we could put a requirement on this or make it into a variable for stage defaulting to main for people who don't use the setup stage. What do you think?

**Comment by mortzel** [comment]
I think it would be nice, if you put a default variable for stage.

**Comment by sorrison** [comment]
OK sure, will get to it at some stage, happy to take a pull request too.

**Comment by sesom42** [comment]
I'm a puppet newbie and can't submit a pull request... But I can confirm this error on Debian 8, Puppet 3.7.2.

**Comment by sorrison** [comment]
Stages have been removed so closing this
