### ISSUE TITLE
Grants via update user fails in mariadb 10.4+

### ISSUE THREAD

**Issue by mead** [NeCTAR-RC/puppet-mariadb#25]
The current method to update privileges for a user in lib/puppet/provider/database_grant/mysql.rb doesn't work in mariadb 10.4+ due to changes making the mysql.user a view rather than a table.

From https://mariadb.com/kb/en/mysqluser-table/ 

> In MariaDB 10.4 and later, the mysql.global_priv table has replaced the mysql.user table, and mysql.user is now a view.

This results in the `update user set` used in lib/puppet/provider/database_grant/mysql.rb failing with:

```ERROR 1356 (HY000) at line 1: View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them (corrective)```

It appears GRANT statement should be used to replace the use of `update user`.

**Comment by sorrison** [comment]
Thanks for the bug report, we have a patch in progress and should be fixed soon

**Comment by sorrison** [comment]
Fixed with 09e2f1a72b9134539c171dfecf901010765c11b1
